import React, { useState } from "react";
import Head from "next/head";
import Footer from "../UI/Footer";
import Navbar from "../UI/Navbar";
import Sidebar from "../UI/Sidebar";

const MainLayout = ({ children }) => {
  const [open, setOpen] = useState(false);
  const [showBackdrop, setShowBackdrop] = useState(false);

  // console.log(open);

  return (
    <div className="bg-white">
      <Head>
        <title>The Lion Tutors</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/lion.png" />
      </Head>
      <Sidebar
        open={open}
        setOpen={setOpen}
        showBackdrop={showBackdrop}
        setShowBackdrop={setShowBackdrop}
      />
      <Navbar open={open} setOpen={setOpen} setShowBackdrop={setShowBackdrop} />
      {children}
      <Footer />
    </div>
  );
};

export default MainLayout;
