import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/UI/Navbar";
import styles from "../styles/Home.module.css";
import tutorIllustration from "../assets/images/teacher-illustration.jpg";
import tutor from "../assets/images/teacher.png";
import Button from "../components/UI/Button";
import TestSection from "../components/UI/TestSection";
import Card from "../components/UI/Card";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-white">
        <Navbar />
        <main className="container mx-auto max-w-screen-xl">
          <section className="bg-white mx-auto p-4 items-center lg:flex md:p-8">
            <div className="space-y-4 flex-1 sm:text-center lg:text-left">
              <h1 className="text-white font-bold text-4xl xl:text-5xl">
                <span className="text-emerald-500">
                  Learn from Expert Tutors with us today
                </span>
              </h1>
              <p className="text-gray-700 max-w-xl leading-relaxed sm:mx-auto lg:ml-0">
                It is a long established fact that a reader will be distracted
                by the readable content of a page when looking at its layout.
                The point of using Lorem Ipsum
              </p>
              <div className="pt-10 items-center justify-center space-y-3 sm:space-x-6 sm:space-y-0 sm:flex lg:justify-start">
                <Button>
                  <p className="text-lg font-medium"> Find Tutors Now</p>
                </Button>
                <a
                  href="javascript:void(0)"
                  className="px-7 py-3 w-full bg-gray-700 text-white font-medium text-center rounded-md block sm:w-auto"
                >
                  Post a Job
                </a>
              </div>
            </div>
            <div className="flex-1 text-center mt-7 lg:mt-0 lg:ml-3">
              <Image
                src={tutor}
                alt="Tutor illustration"
                className="w-full m-auto sm:w-10/12 lg:w-full"
              />
            </div>
          </section>
        </main>
        <main className="bg-gray-100">
          <section className="container mx-auto max-w-screen-xl py-6 dark:bg-gray-800 dark:text-gray-100">
            <div className="container p-4 mx-auto space-y-16 sm:p-10">
              <div className="space-y-4">
                <h3 className="text-primary text-2xl font-bold leading-none sm:text-4xl">
                  Find the best tutor
                </h3>
                <p className="max-w-2xl dark:text-gray-400">
                  At a assumenda quas cum earum ut itaque commodi saepe rem
                  aspernatur quam natus quis nihil quod, hic explicabo doloribus
                  magnam neque, exercitationem eius sunt!
                </p>
              </div>
              <div className="grid w-full grid-cols-1 gap-x-6 gap-y-12 sm:grid-cols-2 lg:grid-cols-4">
                <Card />
                <Card />
                <Card />
                <Card />
              </div>
            </div>
          </section>
        </main>

        <footer className=""></footer>
      </div>
    </>
  );
}
