import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/UI/Navbar";
import styles from "../styles/Home.module.css";
import tutorIllustration from "../assets/images/teacher-illustration.jpg";
import Button from "../components/UI/Button";

export default function Home() {
  return (
    <div className="bg-gray-100">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <main className="container mx-auto max-w-screen-xl ">
        <section className="bg-gray-100 mx-auto p-4 items-center lg:flex md:p-8">
          <div className="space-y-4 flex-1 sm:text-center lg:text-left">
            <h1 className="text-white font-bold text-4xl xl:text-5xl">
              <span className="text-emerald-500">
                Learn from Expert Tutors with us today
              </span>
            </h1>
            <p className="text-gray-700 max-w-xl leading-relaxed sm:mx-auto lg:ml-0">
              It is a long established fact that a reader will be distracted by
              the readable content of a page when looking at its layout. The
              point of using Lorem Ipsum
            </p>
            <div className="pt-10 items-center justify-center space-y-3 sm:space-x-6 sm:space-y-0 sm:flex lg:justify-start">
              <Button>
                <p className="text-lg font-medium"> Find Tutors Now</p>
              </Button>
              <a
                href="javascript:void(0)"
                className="px-7 py-3 w-full bg-gray-700 text-white font-medium text-center rounded-md block sm:w-auto"
              >
                Post a Job
              </a>
            </div>
          </div>
          <div className="flex-1 text-center mt-7 lg:mt-0 lg:ml-3">
            <Image
              src={tutorIllustration}
              alt="Tutor illustration"
              className="w-full m-auto sm:w-10/12 lg:w-full"
            />
          </div>
        </section>
      </main>

      <footer className=""></footer>
    </div>
  );
}
